/* Asadur Rahman (SUKD1702099)
 * Dibakar Sutra Dhar (SUKD1802273)
 * Nandita Dhanda ()
 * Abdourahmane Diallo ()
 * Mohamed Abdellah Abdelhag ()
 * Ahmed Aref Ahmed ()
 */
package pet.hotel.system;

import javax.swing.*;
import java.util.*;
import java.io.*;

public class AddNewCust extends javax.swing.JFrame {
    
  ArrayList<InfoOnReg> Registration;

    /**
     * Creates new form AddNewCust
     */
   public AddNewCust() {
        initComponents();
        this.setLocationRelativeTo(null); // center the form in screen.
        Registration = new ArrayList<InfoOnReg>(); // initializing the array list
        populateArrayList(); 
        
        
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dog", "Cat" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female"}));
        
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dalmation", "Beagle", "Chinhuahua", "Pitbull", "German Shepherd", "Siamese", "Persian", 
                        "Javanese", "Balinese", "Bengal"}));

        
        

    }
     public void populateArrayList() // Array method to store data
    {
        try
        {
            FileInputStream file = new FileInputStream("InfoOnRegistration.dat");
            ObjectInputStream inputFile = new ObjectInputStream(file);
            
            boolean endOfFile = false;
            
            while (!endOfFile )
            {
                 try
                 {
                     Registration.add((InfoOnReg)inputFile.readObject());
                 }
                 catch (EOFException e) //end of file exception
                 {
                     endOfFile = true;
                 }
                 catch (Exception f)
                 {
                     JOptionPane.showMessageDialog(null, f.getMessage());
                 }
            }
                inputFile.close();
        }
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    
    
    } 
     
    public void saveRegistrationToFile()
    {
        try
        {
            FileOutputStream file = new FileOutputStream("InfoOnRegistration.dat"); 
            ObjectOutputStream outputFile = new ObjectOutputStream(file);
            
            for (int i = 0; i < Registration.size(); i++ )
            {
                outputFile.writeObject(Registration.get(i)); // Registration is the array list; get(i) takes the objects and saves to file called InfoOnRegistration.dat  
                
            }
            outputFile.close(); // closes the file
            
            JOptionPane.showMessageDialog(null, "Successfully saved!"); // when the file closes shows the message "File has been successfully saved". 
            this.dispose(); // closes the window after showing the above message.
        }   
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Cust_Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Cust_Address = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Cust_Email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Cust_Ph_No = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Pet_Name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Arrival_date = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Departure_date = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Information of Customer");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create a new customer by entering the data below: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 46, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Customer Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 93, -1, -1));
        getContentPane().add(Cust_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 87, 325, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Customer Address:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 127, -1, -1));

        Cust_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cust_AddressActionPerformed(evt);
            }
        });
        getContentPane().add(Cust_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 121, 325, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Customer E-mail:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 163, -1, -1));

        Cust_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cust_EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Cust_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 157, 325, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Customer Phone Number:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 197, -1, -1));

        Cust_Ph_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cust_Ph_NoActionPerformed(evt);
            }
        });
        getContentPane().add(Cust_Ph_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 191, 325, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Pet Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 231, -1, -1));
        getContentPane().add(Pet_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 225, 325, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Pet Type:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 264, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Pet Sex:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 296, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Breed:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 328, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Arrival Date:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 361, -1, -1));
        getContentPane().add(Arrival_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 355, 325, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Departure Date:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 395, -1, -1));

        Departure_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Departure_dateActionPerformed(evt);
            }
        });
        getContentPane().add(Departure_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 389, 325, -1));

        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 435, -1, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Information on Registration");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 6, 285, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 259, 325, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 291, 325, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 323, 325, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 540));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cust_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cust_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cust_AddressActionPerformed

    private void Cust_Ph_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cust_Ph_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cust_Ph_NoActionPerformed

    private void Departure_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Departure_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Departure_dateActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        
        
        if ( Cust_Name.getText().isEmpty() || Cust_Address.getText().isEmpty() 
                || Cust_Email.getText().isEmpty() || Cust_Ph_No.getText().isEmpty()
                || Pet_Name.getText().isEmpty() ||  Arrival_date.getText().isEmpty() || 
                Departure_date.getText().isEmpty()
                )
        {
            
            JOptionPane.showMessageDialog(null, "Please enter all fields!");
    
        }
        else 
        {
                    String name = Cust_Name.getText().trim();
                    String address = Cust_Address.getText().trim();
                    String email = Cust_Email.getText().trim();
                    String phNum = Cust_Ph_No.getText().trim();
                    String petName = Pet_Name.getText().trim();
                    String petSex =  (String)jComboBox1.getSelectedItem();
                    String pettype = (String) jComboBox2.getSelectedItem();
                    String breed = (String) jComboBox3.getSelectedItem();
                    String arrival_date = Arrival_date.getText().trim();
                    String departure_date = Departure_date.getText().trim();
        
                    InfoOnReg infoonreg = new  InfoOnReg(name, address, email, petName, pettype, petSex, breed, Double.parseDouble(phNum), arrival_date, departure_date ); 
                    Registration.add(infoonreg);
                    saveRegistrationToFile();
                   
       
        }
                
                
                
                

                  
    }//GEN-LAST:event_SaveActionPerformed

    private void Cust_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cust_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cust_EmailActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewCust().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Arrival_date;
    private javax.swing.JTextField Cust_Address;
    private javax.swing.JTextField Cust_Email;
    private javax.swing.JTextField Cust_Name;
    private javax.swing.JTextField Cust_Ph_No;
    private javax.swing.JTextField Departure_date;
    private javax.swing.JTextField Pet_Name;
    private javax.swing.JButton Save;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
